### ISSUE TITLE
[subviews] main gui testing tracker

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1054]
Now that all cg is as fine as before or better, I've moved to testing the main gui, except for dialogs.

- [x] bg1
- [x] bg2
- [x] pst
- [x] iwd1
- [x] iwd2
- [x] gamedemo

TODO:
- [x] dialog, dialog transitions
- [x] exit popup dialog
- [x] exit main menu popup dialog
- [x] worldmap travel
- [x] level up
- [x] bg2 contingency / sequencer window
  - [x] stored window for the same
- [x] bg2 spell immunity / nahal / subspell selection
- [x] plenty bg2 cg button focus issues remain, so one can't speedrun cg
- [x] guistore
- [ ] subspell selection silently doesn't work

**Comment by MarcelHB** [comment]
In some game, the exit dialog in the main menu always quits, regardless of pressing "Cancel". Watch out for that, I don't remember right now.

**Comment by lynxlynxlynx** [comment]
Works fine for me in all games, testing from in game.

**Comment by MarcelHB** [comment]
It's BG. I see the following assertion error:
```
[ResourceManager/ERROR]: CouldAssertion failed: target == NULL || target->IsVisible(), file D:/Sources/gemrb_subviews/gemrb/core/GUI/Window.cpp, line 50
```

**Comment by lynxlynxlynx** [comment]
So you go in game, press x, choose cancel and boom? That works here.

**Comment by MarcelHB** [comment]
No, just the shortest way to exit from the main menu after launching. But I don't have ToTSC installed here.

**Comment by lynxlynxlynx** [comment]
Ah, that one I can reproduce.

**Comment by lynxlynxlynx** [comment]
Dialog testing went quite fine, only found a new spacing problem in bg1&pst. Hard to find dialogs with long replies, but that's also not always the trigger, so /shrug.

**Comment by lynxlynxlynx** [comment]
Levelup testing went well and should be now fine everywhere (dualclassing also works). Or at least everywhere but pst, since that worked recently and is still being worked on.

Store/bag testing was worse, so I stopped it until we restore some functionality.

**Comment by chilvence** [comment]
Hm? There are no actual dual class characters in PST in the BG/IWD sense. I was only testing that in BG1/2 because I didn't want to mess up while merging the "LevelDiff" functionality which I needed to implement the spell slot calculation (I really, really didn't want to duplicate anything...)

TNO's multiclassing should also be working fine now - you could already change class before, it was just the XP assignment and class level tracking that was missing. The only remaining thing I am not sure about is how his caster level is decided, but magic is now the last big task to tackle.

The level up stuff I am still working on is more about removing redundancy, nothing new or exiting, just things like Thac0 calculation, HP, Lore, Saving throws, etc, which is all duplicated in pst/GUIREC.py (either that or it came first, not actually sure which way around). It is all stuff that wasn't broken before, I just felt like if the rules are near identical in all games but IWD2, there should really only be one set of '2nd edition' routines. For example, to ease bugfixing, modding, readability, help with eventual migration to python 3 etc etc .

I've actually been finished with it for a while now, it's just the testing part I need to get around to. But basically, I have not noticed any bugs in the PST level up code as it is now. In fact overall it should be working better in subviews than it is in master :)

**Comment by lynxlynxlynx** [comment]
I guess I wasn't very clear: I only meant I didn't test pst.

Caster level should be the mage level like everywhere else — I see no reason for that to be any different.

**Comment by chilvence** [comment]
Ah I see - well, in any case, level up should all be fine

**Comment by lynxlynxlynx** [comment]
Some more testing:
- sequencer stuff is now ok or was missing even before
- plenty bg2 cg button focus issues remain, so one can't speedrun cg
- subspell selection silently doesn't work

**Comment by lynxlynxlynx** [comment]
Ok, stores should be now fine everywhere, though I did the mistake of testing pst last. Also don't know where to test rumours or donations — the windows are there, just don't know if it's used at all in game.
