### ISSUE TITLE
[feature] improved pathfinding meta bug

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#106]
The pathfinder needs to fulfil several requirements:
- [ ] work well for long paths
- [x] support on-the-fly recalculation (a better path may become available)
- [ ] support NPC bumping — ignoring neutral and friendly characters (and anyone with IE_NPCBUMP set) when checking the search map
  - [ ] and  eventually pushing them away if they're in the way
- [ ] not get all tangled up when the whole party moves or one pc temporarily blocks the path (connected to previous points)
- [x] consider all 16 directions, not just 8
  - [ ] the movement should follow it
- [x] support arbitrary waypoints (currently not exposed to the user yet #107)
- [x] track moving targets (eg. enemies attacking; someone wanting to start a dialog)
- [x] be efficient?

new:
- [x] work well for long paths
- [x] support on-the-fly recalculation (a better path may become available)
- [x] support NPC bumping — ignoring  characters when checking the search map, until they're physically blocking you
  - [x] and  eventually pushing them away if they're in the physical way (eg. blocking a door)
- [x] not get all tangled up when the whole party moves or one pc temporarily blocks the path (connected to previous points)
- [x] consider all 16 directions, not just 8
  - [x] the movement should follow it
- [x] support arbitrary waypoints
- [x] track moving targets (eg. enemies attacking; someone wanting to start a dialog)
- [x] be efficient

IsParyMember()? Then can ignore and bump anyone with GetStat(IE_EA) < EA_EVILCUTOFF.
If GetStat(IE_NPCBUMP) > 0 one can bump everyone.
Other cases can't bump anyone.
Since our search map doesn't store actor info, we need to add more bits and rethink the uses of PATH_MAP_PC/PATH_MAP_NPC/PATH_MAP_ACTOR, so we can infer more about the setter of the blocked area.

kmfrick is working on a theta* based pathfinder.

Good test cases:
- bg1: thief maze (long narrow winding paths), firewine ruins (convoluted)
- bg2: chateau irenicus (very long winding path: ellesime room -> cambion; close most central doors)
- bg2: slums (many random walkers, random fly)
- bg2: coronet: tight spaces — kitchen, stairs; seated patrons, all good for testing bumping; lehtinan vs hendak cutscene (ai movement)
- iwd2: just getting off the main pier
- pst: any, running (for backoff timing)

**Comment by cygarniczka** [comment]
As a 10pp user tangle up issue is very noticeable. Only one npc is enough to block movement of your entire party.

**Comment by lynxlynxlynx** [comment]
Here is a timing test setup and first data (thanks @cygarniczka!).

A script snippet to plug into baldur.bcs / dplayer.bcs / pcname.bcs:
```
IF
  HotKey(V)
THEN
  RESPONSE #100
    ActionOverride(Player1,LeaveAreaLUA("AR4000","",[1198.1891],0))
    Wait(1)
    ActionOverride(Player1,MoveToPoint([478.984]))
END
```
Enable Party AI and press the key to start the sequence. The coordinates are for bg2.

bg1 coordinates: ar2600  [1596.350] to [410.1469]
pst: AR1204 [1418.858] to [2271.1366] (remove second param to LeaveAreaLUA)

Game | distance | time | stdev | n
--------|------------|-------|--------|----
bg2 | 1158.0 | 10.56 | 0.15 | 6
bg1 |

**Comment by cygarniczka** [comment]
Test results for IWD2 is as follow:
5.91s
6.05s
5.50s
5.58s
5.92s
5.38s
5.91s
5.91s
5.96s
5.90s

I couldn't get the IWD script to work

```
IF 
  HotKey(V) 
THEN 
  RESPONSE #100 
    ActionOverride(Player1,LeaveAreaLUA("ar9100","",[952.2642],0)) 
    Wait(1) 
    ActionOverride(Player1,MoveToPoint([2600.1321])) 
END
```

[Icewind Dale - Heart of Winter 4_3_2019 4_36_43 PM.zip](https://github.com/gemrb/gemrb/files/3040651/Icewind.Dale.-.Heart.of.Winter.4_3_2019.4_36_43.PM.zip)

I this zipped video clip I took to show what happens. NPC is shaking in the spot and does not start walking when key is pressed.

**Comment by lynxlynxlynx** [comment]
Excellent work, thanks! I've updated the table and we have some good news — the games are less diverse than we thought, only bg1 is special. :)

**Comment by lynxlynxlynx** [comment]
kjeron had [this to say](https://www.gibberlings3.net/forums/topic/29618-sr-revised-v110-2019-february-5th/?tab=comments#comment-262398): The one thing that is 30' (480h/360v pixels) is PC movement rate per round, at least in original BG1, BG2 bumped it up by 50% to 45' per round.

In bgs a round takes 6 seconds, the 30' hypothenuse is 600, so that brings us to a 100/s, which is what we found experimentally. :) Except that the games are reversed — our results are 75/100, his comment 100/150 per second. Something to keep in mind if we hit any discrepancies after unhardcoding the default speeds in #129.

**Comment by lynxlynxlynx** [comment]
There's some great work in the pathfinder PR as well (it prompted this investigation). It basically works, _just_ actors can still pass through each other, so @kmfrick is investigating other algorithms and ways to fix that with bumping in mind.

**Comment by lynxlynxlynx** [comment]
just realized a good source of the systematic errors above was the perspective - iwd2 has the closest to a straight path.

Since the speeds are given in the horizontal direction, 30' -> 30*16px / 6s (bg1) = 80px/s (69 in iwd, 96 in pst, 120 in bg2). Unless we really screwed up the data, that's too much variation, just from the different round lengths. So some further measurements in vertical and horizontal would be good. Perhaps the typical round timings are ignored and the calculation uses the same constant for all (6s).

**Comment by lynxlynxlynx** [comment]
Ran some tests myself, just measuring horizontal pixel speed:
- pst: 100 px/s, like above; means it takes just shy of a full pst round to travel 30'
- iwd 1&2: 133 or 135 px/s (1/3 more than 100 or 1/2 more than 90 — more likely), means it takes half an iwd round to travel 30'
- bg1: 90 px/s, means it takes 5.33s, a bit less than a bg1 round to travel 30'
- bg2: 120 px/s (same 1/3 speedup vs bg1 as before), takes 2/3 of a bg2 round to travel 30'

This roughly matches kjeron's remark (pst fully, bg1/bg2 with a different ratio, bg1/iwd fully).
