### ISSUE TITLE
Dual class testing meta issue

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#1072]
This is a testing issue to enumerate the possible different dual class combinations and keep track of related issues. 
Some pre-generated dual class ready characters are included, which can be compared with the original game. One reason for this is so I can be sure I didn't break anything with the changes I made in #1067 , but also I can document and fix any other errors I find.

Known issues
- [ ] #328 Gaining multiple levels at once with the last one activating a dual grants HP for all of them.
- [ ] #342 Imoen can cast too many spells after dual-class
- [ ] #819 Berserker to mage dual class goes wrong

Pure class DC combinations

- [ ] Fighter/Cleric
- [ ] Fighter/Druid
- [ ] Fighter/Mage
- [ ] Fighter/Thief
- [ ] Cleric/Fighter
- [ ] Cleric/Mage
- [ ] Cleric/Ranger
- [ ] Cleric/Thief
- [ ] Mage/Cleric
- [ ] Mage/Fighter
- [ ] Mage/Thief
- [ ] Thief/Cleric
- [ ] Thief/Fighter
- [ ] Thief/Mage
- [ ] Ranger/Cleric
- [ ] Druid/Fighter

Kitted DC combinations tested (not all possible ones tested, just a sample from each base class)

- [x] Druid Avenger -> Fighter
- [ ] Ranger Beastmaster 
- [ ] Fighter Kensai
- [ ] Fighter Berserker
- [ ] Cleric of Lathander
- [ ] Swashbuckler
- [ ] Wild mage

 Characters used
[dual class ready characters](https://github.com/gemrb/gemrb/files/5551532/dual.class.ready.characters.zip)

**Comment by lynxlynxlynx** [comment]
If you want to be thorough, also dualclassing into a kit needs to be tested. We don't have the gui for that yet, but characters like that should display and behave properly. You can generate a character in bg1: create a gnome fighter and dc him to a mage. Perhaps that's automatic, but for other races, more schools are available and it definitely throws up a gui.

**Comment by chilvence** [comment]
That's funny, I was just about to ask about dual classing to other kits. It wasn't possible before with BG2, was it?

It would be a pretty neat enhancement feature, in any case. I was trying to see if there was any reason it couldn't be done.

**Comment by lynxlynxlynx** [comment]
Tomsod coded it in a generic way, so yes, it should be possible everywhere for class->kit combos. Kit->kit maybe as a gemrb-only enhancement, but it would require a lot of work.

**Comment by rsantellan** [comment]
Hi @chilvence I'm starting as Fighter Kensai and I do not have the option to dual class.

Have you test it ?

Regards

**Comment by lynxlynxlynx** [comment]
Do you meet the stat prerequisites? You need at least 17 in the new main stat and 15 in one or two secondary ones.

**Comment by rsantellan** [comment]
Sorry! I have items that rise the stats... I will have to start over again.
Thanks a lot!

**Comment by chilvence** [comment]
You can always tweak your savegame with something like [NearInifinity ](https://github.com/NearInfinityBrowser/NearInfinity/wiki)if you have already played through loads of the game. Take points from a different stat if it feels like cheating too much.
