### ISSUE TITLE
Text/Font enhancement meta issue

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1149]
#### Description
while working on #233 I remembered #308 and got set to pondering how we must be doing something wrong with our `Font` rendering. Tugging on that thread quickly revealed that the originals don't create new palettes when changing font colors. Additionally, the `TextArea` and `Label` colors from the CHU are present in the in-memory control structures for each. This led me to conclude that the originals are in fact just somehow blending/tinting the font with the colors.

At this point I remembered our fonts.2da files specify wether or not a font "need" a palette to be created for it. Switching this off leads to `TextArea` text being rendered as a junky looking outline. I was pouring over IESDP/NI and other resources seeing if I could turn up any new info and I remembered that Beamdog themselves released the [data structures](https://github.com/Beamdog/bgfileformats/) that identify one of the TextArea colors as "background".

I now have a theory that these "outline" fonts are tinted with the "background" color, then the inverse of them is tinted with the "foreground" color. The explanation for why this is done would appear to be a poor mans antialiasing. The originals lacked alpha capabilities beyond the color key so the only way to blend a font with the background is to have a carefully crafted outline that you can tint with a specifically chosen color matching the background. It is inexpensive and pretty effective.

I hacked up some code in GemRB to test my theory and the results look pretty good.

an example from how things currently look:
<img width="322" alt="image" src="https://user-images.githubusercontent.com/1126744/107102487-cbd07d00-67d7-11eb-8c5e-b629869a01c8.png">

and an example of the same text rendered with my changes (and a new color):
<img width="329" alt="image" src="https://user-images.githubusercontent.com/1126744/107137500-7fb23500-68ca-11eb-82dd-95cb6f0b4553.png">

original (mind the gamma/brightness difference — unrelated):
![image](https://user-images.githubusercontent.com/121515/107131835-61eccc00-68da-11eb-97a7-c93a06022a53.png)

This screenshot shows the results without the use of `CreateShadedAlphaChannel` which I now suspect should never be used for anything and has always been a hack around lack of proper blending/tinting. It also is done without the `NEED_PALETTE` stuff from fonts.2da.

There is still some cleanup and work to do, but I think this work will resolve #233, #308, and possibly #262. 

### Known Issues
- [x]  Check that drop caps look like original
- [x]  figure out what I messed up with `TextArea` select options. they aren't getting any colors at all.
- [x]  figure out correct colors for world map icon labels
- [x]  tooltips need to have a color assigned. is this different for all games?
- [x] check subtitles. IWD2 subs were ugly before, do they work now?
- [x] We can either rework TTF fonts to work with this background outline concept (might address #1048) or add a field to `Font` to have a flag when it has a background and always set it to `false` for TTF fonts.
- [ ] labels created in GUIScripts probably need the `UseColor` bit set/cleared depending on the font in use. See GemRB label in IWD start screen

**Comment by lynxlynxlynx** [comment]
Added a screenshot from the original, but it looks like you have the journal already sorted.

**Comment by bradallred** [comment]
it appears that using a black foreground with the `0xf0b08000` color from the old fonts.2da as the background looks perfect for the bg2 tooltips, but I'm guessing the other games would require different values (probably print without tint)

**Comment by lynxlynxlynx** [comment]
iwd2 button text is all messed up:
![image](https://user-images.githubusercontent.com/121515/107201597-796ea680-69f9-11eb-8c55-915db94b9b73.png)

Do you need help with researching / looking up anything in particular?

**Comment by bradallred** [comment]
yes, some information gathering on what is broken would be nice.

For the IWD2 buttons, it looks like IWD2 button fonts are inverted. Switching the fg and bg color fixes them. Seems like we may need another game flag and to find out which games need it. An alternative solution may be to add just another `font::print` override that only does tinting since the main issue is that the button fonts don't actually have a "background".

We need to check the games for tooltip colors. I have BG2 and IWD sorted out. I imagine games that don't have fancy TT backgrounds (so all bug BG2?) are the same as IWD.

if you run across labels that are broken, check the GUIScripts to see if we are manually setting a color. Might be we just need to remove that. In fact, I wonder if any GUIScripts actually need to manually set colors anymore. I imagine we did this because we didn't actually understand font coloring before.

**Comment by bradallred** [comment]
We need to generate a list of all the fonts that use a background for all the games. Anything assigned to a `TextArea` (except for the drop caps). Putting this in fonts.2da will allow us to fix the button text in IWD2, the TTF fonts, and mitigate added memory consumption from da07ca3

**Comment by bradallred** [comment]
IWD2 labels appear to be fixed via 26cb142 as well

**Comment by FrElvire** [comment]
In IWD1 on loading windows, "loading game" is black as seen in #1154 screenshot. Are some colors missing ?

**Comment by lynxlynxlynx** [comment]
tooltips are almost all off:
- bg1, bg2: whitish halo, as if there should be no bg color or it should be blended
- iwds: similar problem, but hard to see which layer is wrong — should just display white
- pst: inverted
- demo: ok (ttf font)

**Comment by lynxlynxlynx** [comment]
@FrElvire: no, the colors just weren't adjusted for the new way data is treated. That screen is one we provide ourselves (guils), so it's not hard to invert the colors. It goes by too fast for me to be able to tell if it's perfect now.

**Comment by bradallred** [comment]
yes, this has already been established above. As I said earlier BG2 requires color `0xf0b08000` or thereabouts (thats the old color from fonts.2da, no idea what the original would have been) IWD1 seems to just be white on black. I don't know about the others. We probably should add a setting in gemrb.ini to control the colors.

TTF fonts aren't going to be affected since they don't have backgrounds (yet anyway)

**Comment by bradallred** [comment]
here is a potentially helpful excerpt from BGEE.lua which may help us hone in on some of the colors used for various texts:

```
font_colors={}
--not from bgee. doesn't seem to be used in dragonspear:
-- font_colors['REALMS'] 	= '0xFFE2DDCF'
-- font_colors['NORMAL']	= '0xFF2C2121'
-- font_colors['STONESML']	= '0xFFCECECE'
-- font_colors['STONEBIG']	= '0xFFBCBCBC'
-- font_colors['INITIALS']	= '0xFFB98C00'
```
...
```
fontcolors = {}
-- AABBGGRR
fontcolors['1'] = 'FFCAE2E9' -- title
fontcolors['2'] = 'FFCAE2E9' -- title highlight
fontcolors['3'] = 'FFCAE2E9' -- subtitle
fontcolors['4'] = 'FFEEFFFF' -- subtitle highlight
fontcolors['5'] = 'FF000000' -- parchment
fontcolors['6'] = 'FFEEFFFF' -- parchment highlight
fontcolors['7'] = 'FF000000' -- alternate parchment
fontcolors['8'] = 'FF102526' -- alternate parchment highlight
fontcolors['9'] = 'FFCDD6D9' -- semitrans dark background
fontcolors['A'] = 'FFFDE6E9' -- semitrans dark background highlight
fontcolors['B'] = 'FFCECECE'
fontcolors['C'] = 'FFC8F0C8' -- Minty update color
fontcolors['D'] = 'FF96C8FF' -- orangy subtitle color
fontcolors['R'] = 'FF0000FF' -- red
fontcolors['G'] = 'FF00FF00' -- green
fontcolors['M'] = 'FF000080' -- parchment red
fontcolors['$'] = 'FF82E6FF' -- gold yellow/orange
```

notice that these colors are in `AABBGGRR` format

**Comment by lynxlynxlynx** [comment]
I think a new table would be better, since it's easier to get the data that way — we'll need a bunch of other entries for #137 and #102.

**Comment by FrElvire** [comment]
> @FrElvire: no, the colors just weren't adjusted for the new way data is treated. That screen is one we provide ourselves (guils), so it's not hard to invert the colors. It goes by too fast for me to be able to tell if it's perfect now.

There is no change, "loading game" text is black. 

Do you want a separate issue ?

**Comment by FrElvire** [comment]
Iwd1 buttons are messed up too

![text_color](https://user-images.githubusercontent.com/55502325/108670305-f52f1f80-74de-11eb-86cf-44e1f14fb024.png)

**Comment by bradallred** [comment]
we are aware of all the tooltips being messed up

the loading game text probably also needs to have the "color" bit set in the CHU

**Comment by lynxlynxlynx** [comment]
Reinstated the loading color fix.

**Comment by bradallred** [comment]
let me know if any games still have tooltip issues

**Comment by FrElvire** [comment]
From what I tested it seems ok to me (loading screen included) :+1:

**Comment by MarcelHB** [comment]
PST and IWD have some font issues around spell books and spell information windows:

![iwd_spell](https://user-images.githubusercontent.com/238558/111395175-8c415e80-86bc-11eb-84af-43c3625d6da4.jpg)
![iwd_spell2](https://user-images.githubusercontent.com/238558/111395178-8e0b2200-86bc-11eb-801d-5def75d5ddbc.jpg)

**Comment by bradallred** [comment]
are there any other known issues, or should I close this?

**Comment by lynxlynxlynx** [comment]
I see only two problems and they're not related to this, so let's close and open new ones if it turns out we missed something.
