### ISSUE TITLE
demo: showcase more subsystems / add more data

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1210]
This is a continuation of #313, where stage 1 and 2 were laid out and implemented. To keep it more manageable, I've split it apart. This process will probably need to be repeated as we figure out everything that needs to be done — the previous list grew and changed organically as features were implemented and better understood.

# Stage 3

PVRZ support  #1099:
- [ ] change placeholder forcefield "door" bam to [this beauty](https://opengameart.org/content/animated-portal-or-wormhole-several-variants) or a non-dithered version of the current one
  - [ ] add a "dispel" sort of visual to the disabling cutscene
- [ ] add puzzle step completion effects (eg. buzzing light over related monolith)

Area 2 (interior):
- [ ] **TODO: design the content, expand this list**
- [ ] create mini-map (MOS image) by scaling the base map down by 10.6666666666667
- [ ] add entrance and fix the travel region from outside to point to it
- [ ] add travel region to outside, another entrance to the cave mouth if needed and connect the two
- [ ] add to worldmap (use index 1 for the icon)
- [ ] add general area music (main ambient); ~perhaps [cave ambiance](https://opengameart.org/content/fantasy-sound-effects-library) or [this](https://opengameart.org/content/trembling-mists)~ already selected from a studio album
  - [ ] maybe a subambient in one of the caverns?
- [ ] add overground container / chest, [eg.](https://opengameart.org/content/treasure-pack)
- [ ] on exit: `SetGlobal("ReturnedOutside","GLOBAL",1)`

# Stage X - for later / to be fleshed out

Not fleshed out yet and out of scope until most of Stage 2 is done.

Area 1 (exterior):
- [ ] night wed?
- [ ] night area animations
- [ ] night music

GUI:
- World map travelling
- Add tooltips to relevant elements
  - [x] tooltip background image
-  [ ] Stats window ala simple GUIREC (just add to the designated area in the inventory window)
-  [ ] journal window
  -  [ ] add journal entries for events in the demo
- [ ] Saving and loading?
- [ ] item pickup and drop sound (copy over itemsnd.2da and amend it) once we have more items
- cursors:
  - [x] open/close door
- [ ] character generation?

**TODO: COMBAT**
- [ ] set up protagonist's stats
- [ ] add player portrait to indicate hp/damage
- [x] attack cursor
- [ ] add some traps for boss fight in Area 2?
- [ ] add injured status stuff, so tooltips will display it
- enemies https://opengameart.org/users/marcintokarski https://github.com/gemrb/gemrb-assets/pull/1#issuecomment-801438838
- weapons
- item abilities
- [ ] combat music
- [ ] swing (and hit?) sounds, eg. [these swooshes](https://opengameart.org/content/rpg-sound-pack)
- [ ] Actor combat verbal commands, consider:

> 9 BATTLE_CRY1
> 10 BATTLE_CRY2
> 11 BATTLE_CRY3
> 14 ATTACK1
> 15 ATTACK2
> 18 DAMAGE
> 19 DYING
> 20 HURT
> 65 CRITICAL_HIT
> 66 CRITICAL_MISS

- ...

**TODO: SPELLCASTING**
- [x] casting cursor
- [ ] Actor casting verbal commands & voiceover: `71 VB_SPELL_DISRUPTED`
- [ ] add some spells (plus add their opcodes to effect.ids)
- [ ] create icons for them, [eg.](https://opengameart.org/content/painterly-spell-icons-part-1), [eg.](https://opengameart.org/content/700-rpg-icons)
- add status icons if any spell effects are persistent
- [ ] add casting glow animation
- [ ] add spell hit animations, [eg.](https://opengameart.org/content/2d-spell-effects)
- ...

Audio:
- NPC voiceover for the spoken lines

## Features / subsystems left to consider / showcase
Parties, Formations
Modal abilities
Ambush areas
Translation support

See here for various resources:
https://gemrb.org/New-game.html#needed-resources
https://github.com/gemrb/gemrb/wiki/Asset-creation-notes

**Comment by davidagnome** [comment]
I've got an music track you could use. It's all software instruments but Rus Balailaika, Celtic Harp, Medieval Record over a bass drum beat.

[gemRB-AmbientMusic-001.mp3](https://github.com/user-attachments/files/28916064/gemRB-AmbientMusic-001.mp3)

**Comment by lynxlynxlynx** [comment]
Thanks. It doesn't really fit either of the current areas. It could replace the main menu tune if we wanted it to be less dramatic, for example. Under what license is it available?
