### ISSUE TITLE
0.9.0 Release checklist

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1255]
Copy from 0.8.8, so irrelevant stuff can be removed from there.

### Release checklist

This is a general release preparation checklist to be used in the final stages of preparing a new release.

Final development:
- [x] Fix or postpone issues in the [milestone](https://github.com/gemrb/gemrb/milestones)
- [x] Triage open pull requests
- [x] Check local stashes
- [x] No Coverity Scan issues
- [x] Set SDL2 as the default backend
  - [x] also on builders (Github Actions, AppVeyor)
- [x] make the demo cleanly end soon after entering the second area
- [x] ensure the new guiscript functions have docs we can convert
- [x] fix the remaining kerning bug in #1233 (an otherwise feature request)?

Beta testing:
- [x] Retest character generation of all games
- [x] Playthrough: Chateau Irenicus to Waukeen's promenade
- [x] Playthrough: TOB up to Saradush
- [x] Playthrough: bg1 prologue
- [x] Playthrough: iwd1 prologue
- [x] Playthrough: iwd2 prologue
- [x] Playthrough: pst to exit of Mortuary
- [x] Playthrough: demo
- [x] Ideally a full game runthrough of one of the compleatable games

Release:
- [x] Finalise choice of version number, eg. v1.2.3
- [x] Update version number in `gemrb/includes/globals.h`
- [x] Final `NEWS` update
- [x] Amend Roadmap in contributing.md (mention #938; py3 + demo + post-subviews + 231?)
- [x] Create the source tarball with `make dist`
  - [x] Add any missing files to the cmake install targets and recreate the tarball
  - [x] Add any new extraneous files to `.gitattributes` and recreate
  - [x] Build it and run the minimal test or more: `gemrb/gemrb -c ../gemrb/GemRB.cfg.noinstall.sample`
- [x] Add a git tag and push it
    ```
        ver=0.9.0
        git tag -a -m "GemRB $ver" v$ver
        git push origin v$ver
    ```

Deployment:
- [x] Promote the new tag to a release on GitHub
- [x] Write docs:
  - [x] Forum announcements
  - [x] Release notes if needed (configuration changes, notes for packagers)
  - [x] History: add subviews to major milestones
  - [x] History: link in subviews explanation/history?
  - [x] highlights: from #95 and Brad's writeup on the wiki, SDL2 backend is now mature and default, is rendering faster?, status of the gl renderer
  - [x] features.md and/or roadmap: short cycle to jump to py3 + post-subviews issue tag
  - [x] amend/remove question: https://gemrb.org/Common-problems.html#4-playing-x-at-larger-resolutions-messes-up-the-gui-parts-are-overlapping-and-flickering
  - [x] Add resolution changing table somewhere (Features) with scaling, subviews and widescreen vs pixel size, resolution choice, need for a mod
    - [x] fix up https://gemrb.github.io/Innovations.html#gui-and-high-resolutions
    - [x] Media: add/replace at least one screenshot, showing high-res
  - [x] Dev-docs: update _Technical start up details_
  - [x] appimage: demo is the internal fallback for no data
- [x] SourceForge
  - [x] Upload source package to SourceForge, maintaining the naming format under Releases
    - [x] Upload any release notes alongside
  - [x] Mark release builds as OS defaults on SourceForge as appropriate; mark the source for everyone else
  - [x] (optional) regenerate android build
  - [x] Test downloads
- [x] Runtime tests of release packages
- [x] record a video changelog? Or resolution option explainer?
- [x] Announce on
  - [x] homepage: _config (bump version), index, news, potentially features/status, install (recheck the new links), include screenshot in news
  - [x] Gibberlings3 forums
    - [x] GemRB forum
    - [x] modding news (a template is available in `admin/announcement.template`)
  - [x] SourceForge project page news section
  - [x] #GemRB in channel and title; Discord channel only if it doesn't propagate there automatically
  - [x] send to gemrb-release@lists.sourceforge.net, contact@gaminonlinux.com
  - [x] reddit, https://www.reddit.com/r/baldursgate/submit , Share->Crosspost to r/opensourcegames 
  - [x] bump version on wikidata

Post-release:
- [x] Run `admin/guidoc_wikifier.sh` (no params needed) and upload the new docs
- [x] Update versions back to the `-git` suffix
- [x] Run `admin/restart_news.sh` to restart the NEWS cycle
- [x] If the manpage changed (`git log v0.8.8.. gemrb.6.in`), adapt the web copy (pandoc can convert it to markdown)

**Comment by lynxlynxlynx** [comment]
Got to out of the Underdark and got bored. Tomorrow it's time. :)

**Comment by lynxlynxlynx** [comment]
It's done, finally. 🥮 
Let's not do it again! 😆
