### ISSUE TITLE
0.9.1 Release checklist

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1379]
Opening to start documenting needed doc fixes post-eventual-release.

Final development:
- [x] Fix or postpone issues in the [milestone](https://github.com/gemrb/gemrb/milestone/6)
- [x] Triage open pull requests
- [x] Check local stashes
- [x] No Coverity Scan issues

Beta testing:
- [x] Retest character generation of all games
- [x] Playthrough: Chateau Irenicus to Waukeen's promenade
- [x] Playthrough: TOB up to Saradush
- [x] Playthrough: bg1 prologue
- [x] Playthrough: iwd1 prologue
- [x] Playthrough: pst to exit of Mortuary
- [x] Ideally a full game runthrough of one of the compleatable games

Release:
- [x] Finalise choice of version number, eg. v1.2.3
- [x] Update version number in `gemrb/includes/globals.h`
- [x] Final `NEWS` update
- [x] Amend Roadmap in contributing.md
- [x] Create the source tarball with `make dist`
  - [x] Add any missing files to the cmake install targets and recreate the tarball
  - [x] Add any new files from fetch-demo-data to the cmake dist target
  - [x] Add any new extraneous files to `.gitattributes` and recreate
  - [x] Build it and run the minimal test or more: `gemrb/gemrb -c ../gemrb/GemRB.cfg.noinstall.sample`
- [x] Add a git tag and push it
    ```
        ver=0.9.1
        git tag -a -m "GemRB $ver" v$ver
        git push origin v$ver
    ```

Deployment:
- [x] Promote the new tag to a release on GitHub
- [x] Write docs (a template is available in `admin/announcement.template`):
  - [x] Forum announcements
  - [x] Release notes if needed (configuration changes, notes for packagers): cmake minimum bump to 3.11, new MSVC runtime needed (fix link), py3, iconv
- [x] SourceForge
  - [x] Upload source package to SourceForge, maintaining the naming format under Releases
  - [x] Upload any release notes alongside as Readme.md
  - [x] Copy generated release builds into Release:
```sh
# run in SourceForge shell
version=0.9.1

cd /home/frs/project/gemrb/Buildbot\ Binaries
mkdir -p ../Releases/$version
cp Windows/AppVeyor/$(ls Windows/AppVeyor/ -1rt | tail -n1) ../Releases/$version/gemrb-win32-v$version.zip
cp Apple/OSX/$(ls Apple/OSX/ -1rt | tail -n1) ../Releases/$version/gemrb-macos-v$version.tar.bz2
cp Linux/$(ls Linux/ -1rt | tail -n1) ../Releases/$version/gemrb-linux-v$version.AppImage
```

  - [x] Mark release builds as OS defaults on SourceForge as appropriate; mark the source for everyone else
  - [x] (optional) regenerate android build
  - [x] Test downloads
- [x] Runtime tests of release packages
- [x] Announce on
  - [x] homepage: _config (bump version), index, news, potentially features/status, install (recheck the new links)
  - [x] Gibberlings3 forums
    - [x] GemRB forum
    - [x] modding news
  - [x] SourceForge project news section
  - [x] #GemRB in channel and title; Discord channel if it doesn't propagate there automatically

Post-release:
- [x] Run `admin/guidoc_wikifier.sh` (no params needed) and upload the new docs
- [x] Update versions back to the `-git` suffix
- [x] Run `admin/restart_news.sh` to restart the NEWS cycle
- [x] If the manpage changed (`git log -p v0.9.0.. gemrb.6.in`), adapt the web copy (pandoc can convert it to markdown)
- [ ] Close old milestone
- [x] update checklist: add gamedemo testing, remove android, add the bug report template bump
- [x] update bug report template: version numbers

**Comment by lynxlynxlynx** [comment]
We're getting close. :) The two graphics regressions are the only worrisome thing, since that has been quite whack-a-moley as changes had been made. Perhaps there are some more string issues, but they should surface once playtesting starts.

**Comment by lynxlynxlynx** [comment]
So far so good, playtesting is a great way to catch regressions. All the chargens seem to work fine again, iwd1, pst, tob all passed the intro test. Bg1 has a small regression in the Gorion's death cutscene, but it doesn't impact the outcome. BGT start is broken, SoA left to check, then a proper runthrough.

**Comment by lynxlynxlynx** [comment]
Ok, a thorough soa run completed and things look mostly prim and proper again. Still investigating a few glitches, the windows wtf/PR remains, but other than that all seems set for a new release. :)

**Comment by lynxlynxlynx** [comment]
Everything is ready and written up, we just need to resolve these last GUIScript changes and determine whether #1688 is a real problem or not.
