### ISSUE TITLE
[enhancement] META: add missing EE bits and pieces

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#164]
In the first stage we want to add all missing pieces for EE-only mods to run on the original games with GemRB (unless they rely on EE data itself). 

Several things need to happen. Many things are supported out of the box already, but this meta bug is a WIP list of TODOs.

- [x] PVRZ format #1099
  - [x] [BAM2](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/bam_v2.htm) format support, [go implementation](https://github.com/Beamdog/bgfileformats/blob/master/bam.go#L72)
  - [x] [adapted TIS](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/tis_v1.htm) format support, [go implementation](https://github.com/Beamdog/bgfileformats/blob/master/tis.go#L37)  + [has a shorter PVR page and different naming convention](https://github.com/gemrb/gemrb/pull/1767#issuecomment-1374480965) + page == -1 means full black
    - [ ] add [water overlay transparency](https://www.gibberlings3.net/forums/topic/30630-water-in-tilesets-classic-vs-ee/) support (see TODO in AREImporter)
  - [x] [MOS2](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/mos_v2.htm) format support
    - [ ] except for pstee, the ees autogenerated the minimaps, so recheck if they are missing for the newly added areas
  - [x] WED2? Is it even used? [go implementation](https://github.com/Beamdog/bgfileformats/blob/master/wed.go#L41) (perhaps also jwed is a useful reference)
- [x] BMPv5 format #2080
- [x] BAMv1 started using its alpha channel (only in the GUI)
  - [x] d1c04fa but add a game flag
- [x] TLK: ees changed the layout and dialog.tlk is now only found in per-language folders
- [x] CRE: new creature flag bits
- [ ] CRE: [new fields in the old unused proficiency fields (see 0x007b)](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/cre_v1.htm)
- [ ] [TOHv2](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/toh_v2.htm) support
- [x] Add GameType == "bg2ee" wrapper to GameCheck and use that instead
- [x] Merge GUIScript changes into bg2, the same way iwd and how are sharing them
- [ ] Once it's good enough, add Autodetect.py with some marker files (check Weidu)
- merge identifiers #2257
- [ ] Tooltips use white text
- [x] Move SavePath block in example configs above the here-be-dragons warning (~/.local/share/gamename on linux)
- [ ] Implement the missing tables from  #348 
  - [ ] set `Game::CurrentCampaign` when parsing campaign.2da
- [ ] support for more lookup/override dirs https://gibberlings3.github.io/iesdp/appendices/override.htm (are they really used? Seems just like a performance degradation)
- [ ] new portrait sizes and (extra) lookup path in user dir (now we manually force the smaller size; SDL3 brings 
[SDL_Folder](https://wiki.libsdl.org/SDL3/SDL_Folder))

Extract actual TODOs from these:
- [x] recheck this [list of novelties](http://gibberlings3.net/forums/topic/25516-a&hl=): some may still need implementing
- [x] check IESDP for new and changed actions
- [x] check IESDP for new and changed triggers
- [x] check IESDP for new and changed opcodes (especially bgee-only files in [_opcodes](https://github.com/Gibberlings3/iesdp/tree/master/_opcodes))
- [x] check all the new 2da files on IESDP #348 
- [x] add new objects

For later:
- [x] WBM: the cartoons are in WEBM format, which our VLC plugin can play ... but not tested
- [ ] search our code for "todo.* ee"
- [ ] [new tokens](http://gibberlings3.net/forums/topic/26064-a&hl=), PRO_CLASS is already there, BP probably not needed (black pits?) and the other one just requires a new entry to bgee's gender.2da
- [ ] ^ [color tags in strings](https://gibberlings3.github.io/iesdp/appendices/charactercreation.htm)
- [ ] SoD uses fog, so readd the setting of WB_FOG and find a good way to visualize it (original sucked)
- [ ] eventually we also have to decide about the GUI layer
  - use [Lupa](https://pypi.org/project/lupa/) or a manual translator, so we can reuse more of our python code?
- [x] #90
- [ ] #93 
- [ ] "hide in plain sight" [is hardcoded](https://www.gibberlings3.net/forums/topic/30936-is-hide-in-plain-sight-hardcoded/?do=findComment&comment=275419)
- [x] #483
- [x] sod added a shorthand for drow equipment destruction: `DestroyAllFragileEquipment(ADAMANTINE)` where the material is a new bit in ITM
- [ ] black pits 1 & 2
  -  they use bpsave/ for save games and SoD reads a lot of metadata from campaign.2da

**Comment by bradallred** [comment]
about `pthreads` since we are updating to c++11 we can just switch to `std::thread` no problem.

**Comment by bradallred** [comment]
I've removed the dependency on pthreads (we don't _really_ need synchronization) and added webm support. I only tested a single webm pixel format (I420), so no guarantees I did everything right for RGB.

**Comment by bradallred** [comment]
looks like I did this, which may need additional attention: 91369f0

**Comment by lynxlynxlynx** [comment]
I don't think we can deduce it from the data itself, so it will eventually need a game flag. Unless it also special-cased 0, which I doubt.

**Comment by Alessandro1970** [comment]
It is very important that BGate EE will be supported, as there is no Apple Silicon (ARM) CPU port for MacOS and Rosetta2 emulation support will be dropped as expected. 
This project of yours is important because it will ensure that BGate does not cease to exist even for new platforms with different processors.

**Comment by lynxlynxlynx** [comment]
I don't know if anyone tried, but we likely already work on M1, one just has to use the original games.

**Comment by bradallred** [comment]
I develop on an M1. Yes, we run just fine on it. I'll open an issue to add ARM arch to the buildbot so our releases dont require rosetta.

**Comment by lynxlynxlynx** [comment]
Opcodes are now mostly done, with some rare ones unimplemented or marked by individual TODOs and plenty of little details best left to playtesting — once we get there. If anyone wanted to test, they would need to modify effect.ids to expose them to spells first.
