### ISSUE TITLE
[meta] Tomsod's bug list

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#171]
@Tomsod found these issues that warrant their own reports, but it would be quite a hassle now:

- [ ] known spells reverse their order on save-load
- [ ] AC bonus from single weapon style isn't displayed (it should be)
- [ ] Con bonus HP does not immediately update after a level up, often leaving the PC wounded
- [ ] (supertricky) related: Con bonus should (?) raise HP as well as max HP
- [ ] bag capacity is tested against the number of item "types", not individual items (ignores stacks)
- [ ] gaining multiple levels at once with the last one activating a dual grants HP for all of them
- [ ] protagonist in BG is apparently supposed to get bonus +10% XP
- [ ] two random encounters in a row (on the same map?) can mess up your location on the world map, leading to a crash [should be impossible to get there twice]
- [ ] modal abilities are activated instantly (so you can spam them)
- [ ] (original-except it shouldn't happen on failure) hiding in shadows makes you invisible immediately (before the per-round roll)

> re-charming can leave PC in hostile state

When one of the PCs is charmed by a hostile caster, it used to be possible to regain the control of them by having another PC re-charm them.  But despite being controllable, they still were shown as red (IIRC), and more importantly, after the charms wore out, the PC still remained red, disabling saving.
However, when I just tested this with a fresh build, re-charming doesn't even work anymore -- the PC remains hostile and uncontrollable.  The bug still remains, however: even though the second charm spell doesn't do anything, it still messes up the first spell's removal, leaving the PC hostile.

> cursor can get stuck, disabling tooltips

I think this is about the little hovertext scrolls ceasing to work after pressing the right mouse button.  The currently displayed scroll, if any, will be stuck, and others won't be displayed, until you press the left button.

> AOE spells can affect disabled enemies on random encounter maps

Some encounter maps have different enemies set to show up at different times of day, so most of the map's creatures will be toggled off and invisible at any given time.  But using an AOE spell (like a fireball) will still affect them.

> hour-based NPC presence and spawn points trigger one hour early [reliable test case needed]

Looking at the code, it's a simple error within the SCHEDULE_MASK macro:
https://github.com/gemrb/gemrb/blob/9466e449e9e2e80ace0c8891d3d481dddfc71891/gemrb/includes/globals.h#L206
It should be `- hour_size/2`, not +.  As it is, e.g. 0:30-1:29 gets converted to 1:00-1:59 and thus bit 1, not bit 0 as it should be.

> sound and animation for effects wearing off from corpses

For instance, Slow plays a sound effect when it runs out.  If you slow some monsters and them kill them, the sound will still play when the spell wears off from the monsters' corpses.  Not sure if that's not present in original, but it's certainly weird.

> RemoveSpell action can remove spent spells [test case where this is relevant?]

I think I noticed this when using aTweaks' scroll scribing tweak.  It normally only lets one select non-spent spells, but if the PC has two instances of the same spell memorized and the leftmost is spent, the spent one will be used up.

> records page cannot handle missile/melee weapon dual-wield

Specifically, game hangs after putting a sling in the left hand and going to the stats page.  I don't think you're supposed to be able to do that at all?  I also once managed to trigger the same error with a sling in the right hand and a mace in the left, but I wasn't able to reproduce it later.

> party leader charisma doesn't affect morale etc.? (most if not all of this was scripted)

If it's scripted then that's okay.  I saw nothing in the code and assumed it was not implemented.

> bad non-ASCII character handling in creature names [where did they get them??]

I play BG in Russian, so there's a lot of weiяd characters.  I think they weren't displayed correctly in the console debug messages, so instead of PC names there were empty strings and I had to guess which is which when reading dumps.

> (original?) failing to disarm a container trap does not trigger it

Nope, just checked the original game, and container traps still trigger on a failed disarm.  Meanwhile in GemRB they not only fail to trigger, they may actually be disabled instead if they're one-time only (I think).

> (original? It's her ring) Imoen starts with 1-8th level mage spells unlocked, and they're not disabled on dual

What ring?  There are 1-6th clerical level and 1-8th mage level slots, one of each, in her CRE file.  Sure, that's not your doing, but the original game apparently had some sanity checks on dual and Imoen didn't end up being able to cast a 8th level spell immediately after dualing.  Perhaps those checks could be replicated.  (To clarify, I'm talking about the BG1 Imoen.)

> (worksforme) mag res can block minor sequencer itself from executing (not its stored spells) [tried with a 100% resistant caster]

Just tried casting a sequencer with Horror and Web on Viconia.  Normally casting those AOE spells on her would mostly succeed, Viconia's MR only preventing them from acting on herself, but in the case of sequencer she's able to nullify them completely, so there's no web animation, for instance.

**Comment by lynxlynxlynx** [comment]
I'll be removing the descriptions as we fix them; they'll always be in the other report for reference. Well, unless someone splits this into separate reports.

For charm they appear purplish, lighter than the unselectable color — quite interesting. Expiry worked fine for me; tested on a pc with vampire dire charm (3) and redomination (1003). Fixed the selection and effect competition now.

Are you sure about SCHEDULE_MASK? IESDP:
> 0x401E Time(I:Time*Time)
> Returns true only if the period of day matches the period in the 2nd parameter (taken from Time.ids). Hours are offset by 30 minutes, e.g. Time(1) is true between 00:30 and 01:29.

**Comment by caillean7** [comment]
> Well, unless someone splits this into separate reports.

I'd do that if you want this picked apart into separate issues? Just can't assign labels, you'd have to that yourself.

**Comment by Tomsod** [comment]
> Are you sure about SCHEDULE_MASK?  [Time trigger quotation]

Yes, as it currently implemented, the `Time()` trigger actually relies on the wrong behavior.  But both it and `Actor::Schedule()` call `GemRB::Schedule()`, which explicitly notes:
https://github.com/gemrb/gemrb/blob/8110286ee262b94171e7e3f507cb8b9b74aa7eb1/gemrb/core/Core.cpp#L224-L226
Also, from the ARE file format description on IESDP, which is directly relevant to this bug:

> Actor appearence schedule. Bits 0-23 each represent an hour of game time. Setting a bit means the actor will appear in the area for the corresponding hour.
Hours are offset by 30 minutes as follows:
bit 23 = 23:30 to 00:29
bit 22 = 22:30 to 23:29
(...)
bit 0 = 00:30 to 01:29

So I suppose `Time()` will need to be tweaked as well.  Good find!

> I'd do that if you want this picked apart into separate issues? Just can't assign labels, you'd have to that yourself.

You, sir/lady, are a hero.

**Comment by caillean7** [comment]
> You, sir/lady, are a hero.

Actually, it's lady, and thank you very much :smiley:

**Comment by caillean7** [comment]
> party leader charisma doesn't affect morale

This thing is resolved, I take it?

**Comment by lynxlynxlynx** [comment]
It's not well understood, so it's completely possible that we're not incrementing/decrementing it everywhere we should. But things like Edwin not wanting to fight Firkraag, if you have a low charisma, is completely scripted.

Thanks for the explosion.
