### ISSUE TITLE
0.9.2 Release checklist

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1769]
### Release checklist

Again creating early to start collecting notes for the announcement / site.

Final development:
- [x] Fix or postpone issues in the [milestone](https://github.com/gemrb/gemrb/milestone/8)
- [x] Triage open pull requests
- [x] Check local stashes
- [x] No Coverity Scan issues

Beta testing:
- [x] Retest character generation of all games
- [x] Playthrough: Chateau Irenicus to Waukeen's promenade
- [x] Playthrough: TOB up to Saradush
- [x] Playthrough: bg1 prologue
- [x] Playthrough: iwd1 prologue
- [x] Playthrough: iwd2 prologue (cleared first area, Phaen)
- [x] Playthrough: pst to exit of Mortuary
- [x] Playthrough: our demo
- [x] Ideally a full game runthrough of one of the compleatable games

Release:
- [x] Finalise choice of version number, eg. v1.2.3
- [x] Amend Roadmap in contributing.md
- [x] Final `NEWS` update
- [x] Update version number in `gemrb/includes/globals.h`
- [x] Add a git tag and push it (make sure to push together with something else, so the build won't be skipped)
    ```
        ver=0.9.2
        git tag -a -m "GemRB $ver" v$ver
        git push origin v$ver
    ```
- [x] Create the source tarball with `make dist`
  - [x] Add any missing files to the cmake install targets and recreate the tarball
  - [x] Add any new files from fetch-demo-data to the cmake dist target
  - [x] Add any new extraneous files to `.gitattributes` and recreate
  - [x] Build it and run the minimal test or more: `gemrb/gemrb -c ../gemrb/GemRB.cfg.noinstall.sample`

Deployment:
- [x] Promote the new tag to a release on GitHub
- [x] Write docs (a template is available in `admin/announcement.template`):
  - [x] Forum announcements
  - [x] Release notes if needed (configuration changes, notes for packagers: switch to c++14 after release)
- [x] SourceForge
  - [x] Upload source package to SourceForge, maintaining the naming format under Releases
  - [x] Upload any release notes alongside as Readme.md
  - [x] Copy generated release builds into Release:
```sh
# run in SourceForge shell
version=0.9.2

cd /home/frs/project/gemrb/Buildbot\ Binaries
mkdir -p ../Releases/$version
cp Windows/AppVeyor/$(ls Windows/AppVeyor/ -1rt | tail -n1) ../Releases/$version/gemrb-win32-v$version.zip
cp Apple/OSX/$(ls Apple/OSX/ -1rt | tail -n1) ../Releases/$version/gemrb-macos-v$version.tar.bz2
cp Linux/$(ls Linux/ -1rt | tail -n1) ../Releases/$version/gemrb-linux-v$version.AppImage
```

  - [x] Mark release builds as OS defaults on SourceForge as appropriate; mark the source for everyone else
  - [x] Test downloads
- [x] Runtime tests of release packages
- [x] Announce on
  - [x] homepage: _config (bump version), index, news, potentially features/status, install (recheck the new links)
  - Gibberlings3 forums
    - [x] GemRB forum
    - [x] modding news
  - [x] SourceForge project news section and gemrb-release mailing list
  - [x] #GemRB in channel and title; Discord channel if it doesn't propagate there automatically
  - [x] New Wikidata release entry and ref: https://www.wikidata.org/wiki/Q1988298

Post-release:
- [x] Run `admin/guidoc_wikifier.sh` (no params needed) and upload the new docs
- [x] Update versions back to the `-git` suffix
- [x] Run `admin/restart_news.sh` to restart the NEWS cycle
- [x] If the manpage changed (`git log v0.9.1.. gemrb.6.in`), adapt the web copy (pandoc can convert it to markdown)
- [x] Close old milestone
- [x] update bug report template version numbers

**Comment by lynxlynxlynx** [comment]
We've already got a really rich changelog and the vsync PR will just make it better. Even before that I was thinking of doing a new release without trying to clear the milestoned stuff. However I'll be away from next Saturday (with a very busy week) until May, so it'll have to wait. Let's keep potentially breaking changes like #1788 for the start of the next cycle.

**Comment by bradallred** [comment]
yeah, #1788 is gonna be a while yet anyway. It's definitely better to merge it at the beginning of a new milestone since it can subtly break things too.

**Comment by lynxlynxlynx** [comment]
How recent? Could've have been my CreateLight regression.

**Comment by lynxlynxlynx** [comment]
Ok, did the prologue of all the games and fixed a few regressions and paper cuts. Other than that, we're in good shape. The formation stuff doesn't affect all the storyline testing and any localized GUI fixes can be quickly tested as well. So the next release is around the corner. :)

I'll go with a full bg1 runthrough this time to top it off.

**Comment by lynxlynxlynx** [comment]
Having trouble with name-your-contributors, so had to stop in the middle of releasing. Also one windows build failed, while another didn't, so that's likely ok, but I'll see when I test it.
