### ISSUE TITLE
0.9.3 Release checklist

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1862]
### Release checklist

Again creating early to start collecting notes for the announcement / site.

Final development:
- [x] Fix or postpone issues in the [milestone](https://github.com/gemrb/gemrb/milestones)
- [x] Triage open pull requests
- [x] Check local stashes
- [x] No Coverity Scan issues

Beta testing:
- [x] Retest character generation of all games
- [x] Playthrough: Chateau Irenicus to Waukeen's promenade
- [x] Playthrough: TOB up to Saradush
- [x] Playthrough: bg1 prologue
- [x] Playthrough: iwd1 prologue
- [x] Playthrough: iwd2 prologue
- [x] Playthrough: pst to exit of Mortuary
- [x] Playthrough: our demo
- [x] Ideally a full game runthrough of one of the compleatable games

Release:
- [x] Finalise choice of version number, eg. v1.2.3
- [x] Amend Roadmap in contributing.md
- [x] Final `NEWS` update
- [x] Update version number in `gemrb/includes/globals.h`
- [x] Add a git tag and push it (make sure to push together with something else, so the build won't be skipped)
    ```
        ver=0.9.3
        git tag -a -m "GemRB $ver" v$ver
        git push origin v$ver
    ```
- [x] Create the source tarball with `make dist`
  - [x] Add any missing files to the cmake install targets and recreate the tarball
  - [x] Add any new files from fetch-demo-data to the cmake dist target
  - [x] Add any new extranoeus files to `.gitattributes` and recreate
  - [x] Build it and run the minimal test or more: `gemrb/gemrb -c ../gemrb/GemRB.cfg.noinstall.sample`

Deployment:
- [x] Promote the new tag to a release on GitHub
- [x] Write docs (a template is available in `admin/announcement.template`):
  - [x] Forum announcements
  - [x] Release notes if needed (configuration changes, notes for packagers): if you ship configs then regenerate them (templates changed)
  - [x] Bring this page up to speed: https://gemrb.org/Text-encodings.html
- [x] SourceForge
  - [x] Upload source package to SourceForge, maintaining the naming format under Releases
  - [x] Upload any release notes alongside as Readme.md
  - [x] Copy generated release builds into Release:
```sh
# run in SourceForge shell
version=0.9.3

cd /home/frs/project/gemrb/Buildbot\ Binaries
mkdir -p ../Releases/$version
cp Windows/AppVeyor/$(ls Windows/AppVeyor/ -1rt | tail -n1) ../Releases/$version/gemrb-win32-v$version.zip
cp Apple/OSX/$(ls Apple/OSX/ -1rt | tail -n1) ../Releases/$version/gemrb-macos-v$version.tar.bz2
cp Linux/$(ls Linux/ -1rt | tail -n1) ../Releases/$version/gemrb-linux-v$version.AppImage
```

  - [x] Mark release builds as OS defaults on SourceForge as appropriate; mark the source for everyone else
  - [x] Test downloads
- [x] Runtime tests of release packages
- [x] Announce on
  - [x] homepage: _config (bump version), index, news, potentially features/status, install (recheck the new links)
  - Gibberlings3 forums
    - [x] GemRB forum
    - [x] modding news
  - [x] SourceForge project news section and gemrb-release mailing list
  - [x] #GemRB in channel and title; Discord channel if it doesn't propagate there automatically
  - [x] New Wikidata release entry and ref: https://www.wikidata.org/wiki/Q1988298

Post-release:
- [x] Run `admin/guidoc_wikifier.sh` (no params needed) and upload the new docs
- [x] Update versions back to the `-git` suffix
- [x] Run `admin/restart_news.sh` to restart the NEWS cycle
- [x] If the manpage changed (`git log v0.9.2.. gemrb.6.in`), adapt the web copy (pandoc can convert it to markdown)
- [x] Close old milestone
- [x] update bug report template version numbers

**Comment by lynxlynxlynx** [comment]
We're much closer to release now. The main things that remain are the pathfinding bugs / salvaging PRs, the GUI refactor blocking a few other things and solving the mac build mess.

**Comment by lynxlynxlynx** [comment]
Done, great job everyone!
