### ISSUE TITLE
0.8.6 final release dance checklist

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#189]
### Release checklist

This is a general release preparation checklist. See [Release.md](https://github.com/gemrb/gemrb/blob/master/gemrb/docs/en/Release.md) for a longer writeup.

Final development:
- [x] Fix or postpone issues in the [milestone](https://github.com/gemrb/gemrb/milestones)
- [x] Triage open pull requests
- [x] Check local stashes
- [x] No Coverity Scan issues

Beta testing:
- [x] Playthrough: Chateau Irenicus to Waukeen's promenade
- [x] Playthrough: TOB up to Saradush
- [x] Ideally a full game runthrough of one of the compleatable games
- [x] Retest character generation of remaining games

Release:
- [x] Finalise choice of version number
- [x] Update both version numbers
- [x] Final `NEWS` update
- [x] Write docs:
  - [x] Forum announcements
  - [x] Release notes
- [x] Amend Roadmap in contributing.md
- [x] `make dist`
- [x] Add a git tag and push it
- [x] Run `admin/guidoc_wikifier.sh` (no params needed) and upload the new docs
- [x] Promote the new tag to a release on GitHub
- [x] Update versions back to `-git` suffix
- [x] `admin/restart_news.sh`
- [x] SourceForge
  - [x] Upload source package to SourceForge
    - [x] Upload any release notes alongside
  - [x] Mark release's AppVeyor build as a Windows default on SourceForge
    - [ ] (optional) regenerate android build
  - [x] Test downloads
- [ ] Runtime tests of release packages
- [x] Announce as per Release.md (only SF, homepage and LGDB left)

******************* SF ***************************
GemRB 0.8.6 released!

The GemRB team is proud to announce a new release.

Two years in the making, this release is as full of fixes and polishing as Tiax is of himself. The most noticeable changes are for BG1 players, since it lacked more audio mechanics than any other game, but all the rest received ample attention as well. Modding is now also easier, but you'll have to wait for the next WeiDU release. The pathfinder upgrade was delayed, but you can expect a state-of-the-art version in the next release, which will focus on finishing the GUI handling rewrite. You can help us get there faster: https://github.com/gemrb/gemrb/blob/master/CONTRIBUTING.md)

You can get GemRB from here on SourceForge. 

Full changelog digest:
[code]
GemRB v0.8.6 (2019-11-24):
  New features:
    - more audio, especially in bg1 and pst
    - sndchann.2da support
    - using bags in stores, NPC breaking points, worldmap travel in pst

  Improved features:
    - better megamod and detectable spells compatibility
    - iwd2 and pst levelup, infopoints, gui feedback, dualclassing, ranges
    - verbal constants, (tobex) opcodes, falling, paperdolls, projectiles
    - pst area animations, multipalette animations
    - bugfixes
[/code]

Thanks to everyone that contributed their time and wit, including:
Askmewho, Beren Minor, bholland, Brad Allred, Bubb, caillean7, countbuggula, cygarniczka, Dan Church, edheldil, Eitan Adler, fizzet, fogobogo, FrElvire, ifyGecko, Ilya Zhuravlev, Jaka Kranjc, Jérôme Duval, Kevin Michael Frick, khelban12, Lyle Hanson, Manuel Alfayate Corchete, MarcelHB, MesmericOrb, Mingun, miqlas, nerd-rage, Nicolás Clotta, skellytz, sten13, Tomsod, tomudo, Wisp and Yorick Hardy. 

*If anyone is wondering what's up with the release name: squirrels didn't land any hits before, due to the way a detail in our combat code was implemented. Now the immortal squirrel of Easthaven can have its revenge.*

https://sourceforge.net/p/gemrb/news/new

******************** LGDB ******************
http://www.lgdb.org/game/gemrb
Visit the project page and submit an update (version, changelog). Choose
"edit current" on the top and scroll through the form to get to the relevant part.
