### ISSUE TITLE
 META: pathfinder performance improvement ideas

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#2076]
Just ideas, some already partially tested. Edit as more are thought of:

- [ ] #1693
  - [ ] IsWalkableTo should work faster when done strictly in the search map space
  - [ ] cache actor Pos in search map space to avoid repeated conversions?
- [ ]  consider splicing sub paths for bumping (instead find the bumped position, then calculate a path from that position to the current position in the path and then prepend that path segment, which would be much better than completely recalculating a path)
- [ ] we probably don't make any effort to avoid calculating a path that will bump again
- [ ] should an actor be able to bump more than one other actor?
- [ ] consider using squared distances in FindPath (at minimum the heuristic factor would need adjusting) to skip a bunch of sqrts
- [ ] #1692
  - [ ] reuse a little bit of information to halve the penalty by skipping the ignore-actors run if there wasn't any actor to potentially bump into https://github.com/gemrb/gemrb/issues/1692#issuecomment-1335998285
- [ ] parallelize FindPath

**Comment by MarcelHB** [comment]
Given some time actual testing now, the path finding, or more likely its use, appears to have serious performance drops when there is a crowding around narrow spaces, like this one:

![iwd2_crowd_path](https://github.com/user-attachments/assets/86547493-595c-4a59-8b06-a0703bd4bdf5)

This is the time lost on this:

![iwd2_crowd_path_tracy](https://github.com/user-attachments/assets/ee14ddb5-be14-4f88-b9a1-90c86a36af58)

IWD2 AR3001 to the south of the entrace is some test case when there are 20+ goblins that you can lure into the tunnel.

**Comment by lynxlynxlynx** [comment]
Did a bunch of conversions for algos to work on the search map directly and it seems to be working fine.
A simple iwd2 test gave:
- GetBlockedInLine went from 1,41% to 0,14% share in callgrind
- GetBlocked from 0,78% to 0% (doubled the amount of the tile version, but small enough not to have any effect )

The real GetBlocked stat is from avoiding calls. Before there were over 3M for both variants together, now less than 0,7M. :) So hopefully it will help a bit with the worst cases.

**Comment by MarcelHB** [comment]
Is there some recent performance problem? It's quite noticable that on maps where NPCs do random-walk, the framerate looks ~30% down.

**Comment by lynxlynxlynx** [comment]
Not to my knowledge, but of course going back to using the navmap more didn't help. I believe @draghan is working on some optimisations.

**Comment by rsantellan** [comment]
> Is there some recent performance problem? It's quite noticable that on maps where NPCs do random-walk, the framerate looks ~30% down.

This is happening to me also, sometimes is really hard to move around, need a lot of patience.

**Comment by MarcelHB** [comment]
Another easy-to-test example: When triggering the alert in Irenicus' dungeon around the dormitory, the golems are supposed to be dispatched. Problem: they may not find a way, could be related to a manually closed door on the way, so the FPS remains significantly lowered, and about every 2s, the cursor becomes noticeably stuck for a bunch of ms. Solution is then to walk to them and attack them in their chamber instead.
