### ISSUE TITLE
META: iwd2 playthrough bugs

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#2158]
While doing the first proper run, I've fixed a few things on the fly, but there's also a growing list of things to look at later:
- [x] my wizard paladin could take weapon specialization, even though it's limited to fighters (probably insufficent featreq.2da check)
- [x] Feat::CombatCasting probably shouldn't be conditional on non-max hp
- [x] why couldn't my mc pick improved critical?
- what's with weapon damage sometimes too high (are we somehow using the alt dice fields?)
  - [x] moonsword especially, since it has the main dice disabled (0d6)
- [x] everyone was unaffected by web
- [x] fist don't do stunning damage here? 8 chambers and RE say they should
- [x] traps in ar6100 don't work at all?
- [x] incendiary cloud surely needs a bigger aoe
- [x] test your saved scrolls
- [x] Mandal's corpse in ar6102 can be discovered from the adjacent tunnels
- [x] can use opposition school scrolls - is that not a bug?
- chunked actors still act now and then #2179
- Conlan's store doesn't work after reporting Sheemish, doesn't even open, prevents saving, can assert ... #2181
- ar6100 izbelah should cast 7 eyes immediatelx after 1st dialog #1665
- GUISPL stacks are broken again: desc window, additional memo, unmemo, wrong lookups when several booktypes #2186
- [x] ar5300 pool thrall effects heard everywhere (should be relative) — is it the druergar trying to go invisible
  - [x] and why does the animation keep playing so often, should it really?
- [x] room floor trap in Chult temple inescapable, trigger inoperable
- [x] shroud of flame does not work?
- [x] should dodge stack with the flamedance talisman?
- [x] 8 chambers strips you of equipment after first fight, not before, and dumps it on the floor (should be the storage bin?)
- weapon sets are all wonky in the inventory already #2202
  - and weapon ability switching is buggy: throwing weapons don't work

**Comment by lynxlynxlynx** [comment]
Re gold amounts: the orcs don't have random loot, just drop the exact amount of gold they're carrying. So when there's several instanced from the same CRE, you get the same loot every time.

**Comment by lynxlynxlynx** [comment]
I edited your post a bit, to make it clearer where I know enough.

- PC morale break only happens after reloading? <-- I think this is just a remnant of the zeroed morale recovery bug. And the normal recovery one reported separately.
- AR6501 treasure room code not working. <-- worked for me, used the solution drawn on sorcerers.net
- Spellbooks I already mentioned in my list, something to look at after the GUI refactor merge
- Annoyingly buzzing sound when standing around the Aurilite doors <-- not sure what you mean; I hear some crackling, but that's clearly an ambient from the shrines inside (which I'd consider a bug in the data, surely they wouldn't use a camp fire for a shrine to the goddess of cold)
- Ambient inside temple playing every few seconds <-- which area? ar4100 looks as intended (main ambient), ar4101 too, but it does have some dramatical area music that you can't not notice it loops — is this what you meant?
- Abishais turn hostile despite promising help. <-- like they say, you probably weren't at full hp
- Level two arena game is buggy starting from 2nd level, instant win of every field. <-- noticed, was relieved, haha
- Sordirskin respawns one by one until the map will be full one day, I guess. <-- who's that? If you mean the barbarians, a big crowd is scripted to appear once you start manipulating the puzzle

**Comment by MarcelHB** [comment]
Ok, will reevaluate once done. I hopefully have enough savegame milestones for this.

**Comment by MarcelHB** [comment]
My first full playthrough in GemRB done. For most of the time it was smooth enough that I wasn't thinking much about _not_ playing the original IWD2 here. In contrast, technically I we now do a better job. At least I find things in the original IWD2 more clunky when playing window mode.

Anyway, the most annoying things by my personal order:

1. Path finding: actors getting stuck by walking into each other, "path abandoned" messages, unnecessary walking distances and actors some following each other asks for way more attention since it's sometimes even hard to discover in crowded battles.
1. Path finding: performance problems on many maps, dropping into something like 10fps.
1. Broken spellbook (didn't had much time left to test this after the big merge recently) and weapon GUI. You can play well without being too smart for switching weapons or using all learned spells, but I hope we can address this soon.

Next I try to re-iterate through my list above to check what is left open/reproducible, and open separate issues.

**Comment by lynxlynxlynx** [comment]
I've opened new issues for what's not handled yet. Currently the only remaining actionable thing are the 3 animation problems.

Need more info / didn't experience it:
- Some enslaved dwarfs blocking the exit gates can't be attacked at all, not even by bow. Seems pathfinding related.
- none in the AR630x section
- "Path abandoned", yet I should be able to execute the action from where standing since it's often very close
- Enemies sometimes not being followed? Not sure what's the original way here but it's like this and that at no apparent pattern. (could just be advanced ai scripting; also some of these actions are interruptible)

**Comment by MarcelHB** [comment]
> I've opened new issues for what's not handled yet. Currently the only remaining actionable thing are the 3 animation problems.

Thanks, didn't managed to return to reproducing these things yet, or lacked the time.

> * Some enslaved dwarfs blocking the exit gates can't be attacked at all, not even by bow. Seems pathfinding related.

Can't reproduce it any more. It was that some dwarves were stuck inside the exit area and weren't able to move or to be attacked.
![iwd2_stuck_dwarfes](https://github.com/user-attachments/assets/feb52e4c-7719-46af-a98d-10c7aa7af01a)

> * none in the AR630x section

Let's ignore this then, I don't have savegames for that I'm sure about the exact state regarding these problems.

> * "Path abandoned", yet I should be able to execute the action from where standing since it's often very close

This is or was quite common. Mostly when having the group close together and applying healing spells, then sometimes nothing happens (cleric won't move).
 
>* Enemies sometimes not being followed? Not sure what's the original way here but it's like this and that at no apparent pattern. (could just be advanced ai scripting; also some of these actions are interruptible)

For enemies that tend to run around (like the drow in AR620x) or run away for panicking, I sometimes noticed my tank PCs to just give up standing around then. Could have been due to being stuck (too close to each other bug), too. Maybe even for valid reasons since I don't know exactly what the original did for these cases.

**Comment by lynxlynxlynx** [comment]
Ok, got the animation stuff fixed locally (the yuan-ti suffer from #2117 as well). Will push with the point refactoring. I'll just close this and we can revisit individual problems as we discover more.
