### ISSUE TITLE
[enhancement] flesh out the included demo

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#313]
This is basically a modding todo. We include a very basic demo with open-licensed data, but it's currently just an area with a simplistically animated character. More assets and use of features would be cool.

# Stage 1
This has already been achieved, a basic runnable demo. The only record we have is the [git history](https://github.com/gemrb/gemrb/commits/master?after=7306dbe9e4ef65b2b8e0bdd5d1cb92b9135b74bb+34&branch=master&path%5B%5D=demo).

# Stage 2

These things can be worked on right now and will gel together well. It's a TODO for the first area and some interface stuff.

Area 1 (grove exterior):
- add some area animations
  - [x] ~some small insect swarm somewhere~
    - [x] indicating a hidden cache - add container
- [x] add a rabbit or other small animal (or two) to area
  - [x] create animation (standing and walking is enough): can reuse [rabbit](https://opengameart.org/content/rabbit-0) or  [rat](https://opengameart.org/content/evil-giant-rat)
  - [x] script it to random walk and flee when approached (don't forget to add used actions and triggers to the ids files)
- [x] shorten shadows in the area background to about a quarter or less
  - [x] fix lightmap to match
- [x] add a forcefield "door", something blocking the entrance to the interior
  - [x] add actual movement blocking
- [x] Infopoints on the monoliths (old language / for deciphering, for riddle)
  - [x] decide if the area graphics need a touch up, so it's clear something is on them
- area script:
  - [x] advance time to night time after reentering and clear the weather if it doesn't phase out on its own
- add puzzle
  - [x] add NPC granting it
  - [x] design the riddles
  - [x] create dialog with all the puzzles and connective tissue
  - [x] fix monolith texts to make sense
  - [x] on final success, trigger a cutscene: rain, lightning, dispel the forcefield enabling access to inside
- create a story:
  - [x] design it
    - perhaps the player going to their village elders to learn of the feats of famous ancestors … one of which you then relive interactively in the demo
  - [x] write the texts
  - [x] displayed in chapter Textscreen for the intro setting of the scene
  - [x] provide motive to go to first area, solve the puzzle (and enter the interior)
  - [x] as a rite of passage, blocking entry into the next area + cutscene ... through one or more npc dialogs

Misc:
- [x] create a nice avatar for the pc
- [x] create nice fog of war
- [x] add ground pile drawing(s) for dropped loot

GUI ([very nice assets](https://opengameart.org/content/rpg-gui-construction-kit-v10) + [extra](https://opengameart.org/content/rpg-gui-contstruction-kit-vmoon)):
- other mouse cursors
  - [x] worldmap scrolling (bg1: open palm and clenching open palm)
  - [x] move targetting
  - [x] inaccessible terrain
  - [x] dialog start
  - [x] infopoint interact
  - [x] container interact
  - [x] travel region interact
  - [x] map edge scrolling, we can use [this](https://opengameart.org/content/dirty-metalstone-cursorsarrows) or [this](https://opengameart.org/content/pointing-arrows)
- add a proper worldmap:
  - [x] pick an image and regenerate the wmp
  - [x] create map icon for exterior area
  - [x] create the we-are-here indicator image (wmdag.bam)
  - [x] add map window
  - [x] add worldmap window
- [x] sync msgwin design with the rest + take up all the space, so continue doesn't stand out
- [x] add pause/unpause game button
- [x] add indicator that game time is running
- [x] add map button
- [x] add some tooltips
- [x] add dialog windows
  - [x] figure out why replies are scrolled out of view - fixed in subviews
- [x] add startup window as in #1050 
  - [x] showcase input by adding a textedit to enter the protagonist name (default to something for quick entry) and set the CHARNAME token to it (currently uses "Seeker")
  - [x] skip it if SkipIntroVideos is set
- [x] simple textscreen for the intro (following "enter demo")
  - [x] skip it if SkipIntroVideos is set

Inventory:
- [x] create a reward item to put inside outside container (diary?): ruby.itm
- [x] inventory window (basic!)
- [x] paperdoll for the avatar
- [x] container window

Audio:
- GUI sounds:
  - [x] button press, unpress
  - [x] window open, close
  - [x] AMB_D18 for opening the container (no close sound)
- Any area animation sounds, as needed
- [x] footstep sounds [(perhaps one of these can be chopped up)](https://opengameart.org/content/fantasy-sound-effects-library)
- [x] add some sound effects to the puzzle cutscene
- [x] [this](https://opengameart.org/content/soliloquy) could work well as intro music
- [x] add cmake target to download music assets and move them to the assets repo
  - [x] add the new target to release builds on the bots
- [x] add general area music (main ambient)
- [x] Actor verbal commands, consider:

> 0 INITIAL_MEETING <-- only for npcs
> 8 BORED
> 
> 26 SELECT_COMMON1
> 27 SELECT_COMMON2
> 28 SELECT_COMMON3
> 
> 32 SELECT_ACTION1
> 33 SELECT_ACTION2
> 34 SELECT_ACTION3
> 
> 62 DIALOG_DEFAULT <-- only for npcs

# Stage X - for later

See #1210

**Comment by lynxlynxlynx** [comment]
Continuing from #1078.

We have a bunch of basic todos for the demo already, but the overall design has not been discussed. Which means it's also harder for people to contribute to making it happen, since it's not all nicely split up into well defined and manageable chunks that clearly help complete the picture.

Is anyone for a quick call to set the scope and define the major ideas we want to have in the demo? I think it would be faster than if we just start writing it up. @m7600 @chilvence, but anyone is welcome to join.

**Comment by chilvence** [comment]
Do you mean like a Zoom meeting or something? I'd be up for joining that if everyone else is, although I don't personally have too many ideas game design related, I do agree on the need to break down the work required into some sort of design doc. 

The hardest part is not even knowing where to start. Not just asset wise, but what direction to go in, like is it serious or silly, or somewhere in the middle? Do we try to imitate the other games setting, or create something unique?

Another repository for the project is also sounding like a good idea. Somewhere where the source assets don't get lost. Something people can checkout with git and see how everything is put together, fiddle with it, hopefully send pull requests.

**Comment by lynxlynxlynx** [comment]
Zoom, Discord, Jitsi, whatever works basically.

For the demo we don't really have to worry about the setting, since it's just a tech demo after all.

**Comment by m7600** [comment]
I can't commit myself to a real-time meeting, unfortunately. But I'll agree to whatever you guys decide for the demo. I don't have a lot of ideas either. Initially I thought that the demo was supposed to be a mini-game, but I think that's out of the question now, if I understand correctly (no combat for example).

**Comment by chilvence** [comment]
Could we not just borrow the combat rules from one of the other games? (I would vote for IWD2's 3rd edition rules if that were the case)

**Comment by chilvence** [comment]
Actually thinking about it, could the demo become a prototype/testbed for [project number 1](https://github.com/gemrb/gemrb/projects/1) ?

**Comment by lynxlynxlynx** [comment]
There's no reason (yet?) to not have combat, it's just way too early. It requires more animations, items, proper stats, some scripting, perhaps more of the interface ...

Any preferred day and time @chilvence?

**Comment by chilvence** [comment]
Any time is fine by me really, I can always pause whatever I have on

**Comment by lynxlynxlynx** [comment]
Hmm, how about today then, so we get it out of the way. Let's say 18:00 UTC on Discord? I'm just assuming you're from GB, so let me know if that time is not good for your timezone. I expect it will take up to half an hour at this stage.

**Comment by chilvence** [comment]
That would be ideal

**Comment by lynxlynxlynx** [comment]
We had a fruitful brainsteering, looking at most of our features and already thinking a bit about the storytelling aspect. The first version of the roadmap is the result of that and can be found in the opening post.

**Comment by chilvence** [comment]
I'm building up a collection of links to websites that we can draw on for basic resources in each category (even if they are placeholders)

In addition to music, I also managed to find about 10  half decent free sound effect websites with royalty free or permissive licences, so when it comes to needing audio, I can probably cover that job

Regarding the GUI design, I think it would be nice to take inspiration from Pillars of Eternity, rather than copy the classic BG/IWD style. I think they did a great job refining the layout, almost like a continuation of the improvement efforts made in IWD2.

**Comment by lynxlynxlynx** [comment]
Yeah, we're free to do it however we want, but it's also true we don't need to make it nearly as complicated.

**Comment by m7600** [comment]
Nice, I like the plan. It's gonna be a lot of work, but I'm sure it will be fun.

**Comment by lynxlynxlynx** [comment]
Ok, map and worldmap are done. Still need to add a button to get there, but one can do it with M already.

**Comment by lynxlynxlynx** [comment]
Added a pretty much complete cursor set to the demo. Of course much of it can't be seen in game yet. And it's only visible in the subviews branch — I worked there since a required refactoring was done there already. But now we support also png cursors. :)

But it fixes no cursor difference for inaccessible areas, no cursor for the travel area, no pressed state ...

Mostly existing ones, but also drew a few new ones. See here for the OGA submission:
https://opengameart.org/content/cursor-set-based-on-tempest-in-the-aether-and-ryzom-core

**Comment by lynxlynxlynx** [comment]
Started writing down notes, lessons learned while working on the demo:
https://github.com/gemrb/gemrb/wiki/Asset-creation-notes

Some nice progress in the meanwhile, but the lack of PVRZ support is a real bummer. As much as I'm itching to have it, since there's a gorgeous area animation waiting for it, it will just have to wait, as finishing subviews has priority. I've pinned the issue in hopes of some new contributor coming along and fixing it, which would be the cutting-the-Gordian-knot solution. 😃

**Comment by lynxlynxlynx** [comment]
Ok, stage 2 is nearing completion. All this searching, drawing and designing is quite a nice break from coding, when I don't have the energy for that. We have a start screen, chapter text, a basic story arc, a bunch of puzzles, a npc, an area animation, a container, a cutscene, a portrait, a bunch of gradients, items and a full-fledged inventory GUI. 

What remains is the audio side and a few animations (see above). The second area can now be added and linked and some demo completion cutscene triggered soon after entry. 

While creating the various GUI controls and assets, I created a bunch of gimp files and intermediaries for bam construction. The size grew faster than I anticipated, so I'll create an assets repo for them. The stuff that is used directly will remain in the main repo, of course, though the size of our downloads will start growing as we add audio and later better animations (PVRZ-based graphics).

- [ ] create an assets repo
- [ ] add demo/ dir
- [ ] add readme
- [ ] move all/most of demo/source + uncommitted there
- [ ] mention repo in demo readme
- [ ] mention repo in site repo list

**Comment by m7600** [comment]
For Stage X, should we add a character creation screen? I think it would be interesting to showcase that in the demo, character creation can be fun by itself, independently of the game. If that's accepted, we would have to decide if it used 2nd edition rules like Baldur's Gate, or 3rd edition rules like Icewind Dale 2. I like both rulesets, so I don't have a strong opinion either way.

**Comment by lynxlynxlynx** [comment]
Perhaps, though I don't see much value in it, since it's just showing off the GUI. Currently you can actually change the name, but it's not very obvious.

**Comment by lynxlynxlynx** [comment]
The outside is pretty much finished. Sure, some things could use some polish, but the thing works and shows off quite a bit of GemRB. :) I'm closing this one in favour of #1210.
