### ISSUE TITLE
0.8.7 Release checklist

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#704]
Don't get excited yet, just opening this to be able to record release-specific items.

### Release checklist

This is a general release preparation checklist to be used in the final stages of preparing
a new release.

Final development:
- [x] Fix or postpone issues in the [milestone](https://github.com/gemrb/gemrb/milestones)
- [x] Triage open pull requests
- [x] Check local stashes
- [x] No Coverity Scan issues

Beta testing:
- [x] Playthrough: Chateau Irenicus to Waukeen's promenade
- [x] Playthrough: TOB up to Saradush
- [x] Playthrough: bg1 to chapter 1
- [x] Playthrough: iwd1 to chapter 2
- [x] Playthrough: pst to Dhall exhaustion
- [ ] Playthrough: iwd2 to chapter 1 (save targos)
- [x] Ideally a full game runthrough of one of the compleatable games
- Retest character generation of remaining games
  - [x] bg1
  - [x] bg2
  - [x] iwd
  - [x] iwd2
  - [x] pst
- [x] Recheck we compile with gcc10

Release:
- [x] start copying the sample config to GemRB.cfg in the build bots https://gemrb.github.io/Install.html#configure-gemrb
- [x] Finalise choice of version number, eg. v1.2.3
- [x] Final `NEWS` update
- [x] Amend Roadmap in contributing.md
- [x] Update version number in `gemrb/includes/globals.h`
- [x] Create the source tarball with `make dist`
  - [x] Add any missing files to the cmake install targets and recreate the tarball
  - [x] Add any new extraneus files to `.gitattributes` and recreate
  - [x] Build it and run the minimal test or more: `gemrb/gemrb -c ../gemrb/GemRB.cfg.noinstall.sample`
- [x] Add a git tag and push it
    ```
        ver=0.8.7
        git tag -a -m "GemRB $ver" v$ver
        git push origin v$ver
    ```

Deployment:
- [x] Promote the new tag to a release on GitHub
- [x] Write docs:
  - [x] Forum announcements
  - [x] Release notes if needed (configuration changes, notes for packagers)
  - https://gemrb.github.io/Install.html#configure-gemrb
    - [x] Remove GemRBPath instruction
    - [x] Remove the copying step
    - [x] Remove windows subsection, the buildbot does the editing now
  - [x] Remove iwd2 resolution instruction from https://gemrb.github.io/Install.html#run-gemrb
- [x] ~ask existing packager if they want to be added to the revived gemrb-release ML~
  - [x] add https://sourceforge.net/projects/gemrb/lists/gemrb-release to release template
- [x] Runtime tests of release packages
- [x] SourceForge
  - [x] Upload source package to SourceForge
    - [x] Upload any release notes alongside
  - [x] Mark release's AppVeyor build as a Windows default on SourceForge and source for everyone else
  - [x] ~(optional) regenerate android build~
  - [x] Test downloads

Post-release:
- [x] Run `admin/guidoc_wikifier.sh` (no params needed) and upload the new docs
- [x] Update versions back to the `-git` suffix
- [x] Run `admin/restart_news.sh` to restart the NEWS cycle
- [x] If the manpage changed, adapt the web copy (pandoc can convert it to markdown)
- [x] create new checklist and add:
  - History: add subviews to major milestones
  - History: link in subviews explanation/history?
  - highlights: from the bug and Brad's writeup on the wiki, SDL2 backend is now mature and default, is rendering faster?, status of the gl renderer
  - next: short cycle to jump to py3
  - [ ] Add resolution changing table somewhere (Features?) with scaling, subviews and widescreen vs pixel size, resolution choice, need for a mod
