### ISSUE TITLE
 META : Overview list for full PST playability

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#825]
Copying the idea from Lynx, I thought a meta issue for keeping track of PST bugs would be handy. 

I find the tracker really amazing and helpful, but it has been hard for me to keep so many different issues to test straight in my head

This is basically a combination of my remaining offline (ie post-it) notes, combined with issues that are already tracked (I've summarised some of the issue names best I could for readability), condensed into one giant list

_"e pluribus unum"_

Gameplay:
- [ ] #176 Verify level up behaviour
- [ ] Multi classing, class levels for TNO are not handled correctly
- [ ] #438 You can respawn if killed in the final fight
- [ ] #521 When you respawn, you should have regenerated more than 1 HP
- [ ] #524 Morte loses his taunt ability
- [ ] #598 Actors that use EscapeArea() should try to walk 'off screen' then timeout
- [ ] #599 You don't get locked in the catacombs because of unpredictable scripting

Magic Spells: _(hiss)_
- [ ] #458, #637 Figure out spell casting/round timings
- [ ] #640 Errant stacking of some spell bonuses
- [ ] #641 Errant permanency of some temporary effects
- [ ] #455 Multiple actor targeting needed for some missile spells
- [ ] #639 Spell behind/in front of actor animations don't work
- [ ] #454 Some spells 'should' make spectators stand around as if dumbfounded
- [ ] #not tracked?: High level spells, figure out what is left to implement

Interface: 
- [ ] #293 Fix Text rendering in options window
- [ ] #307 Reform party window has placeholder graphics
- [ ] #445 Dialog window 'click to close' text should not always appear
- [ ] #450 Anti RSI: The original game has 'shift+click' as a run command
- [ ] #451 Original interface stays visible in cutscenes
- [ ] Thieving skills can't be assigned in UI
- [ ] No visual feedback for active thief skills
- [ ] Items are not always stacked automatically on pickup
- [x] Item stack split isn't working [fixed in my WIP branch]
- [ ] Options menu doesn't pause the game
- [ ] Dying shouldn't deselect you, since you just carry on living regardless...
- [ ] Some animated portrait states are chosen incorrectly
- [ ] Clicking on quick items does not engage target mode until after the floatwindow is closed

_[note: the untracked ones here I prefer to send PR's rather than bug reports]_

Graphical Rendering:
- [ ] #167 Area animation clipping by wall groups
- [ ] #177 Floating text support for combat messages etc
- [ ] The world doesn't seem to get dark at night

Character Animation:
- [ ] #93 Use RESDATA.INI for all games animations
- [ ] #175 Implement missing character stances
- [ ] #522 Need to use per-weapon animations for TNO
- [ ] #523 Spellcasting animations are not used
- [ ] Combat: all actors should change to alert stance, not just hostiles

Sounds;
- [ ] #824 Critical hit lines are incorrect
- [ ] #453 Missing character action feedback lines
- [ ] #452 Missing inventory feedback lines
- [ ] #444 Song Queues for meeting NPC's don't work as expected
- [ ] NPC idle 'Bark' sounds are not used ( probably #93 also ?)
- [ ] Missing weapon attack sounds

Miscellaneous by Area:
- [ ] #537 'Safe zone' in AR1100 (bone desert) is not working
- [ ] #539 Conversation loop in AR0511 (foundry office)
- [ ] #542 Random crashing in AR0605 ("slaking" intellectual lusts)
- [ ] #620 Test what is missing from the Modron Maze
- [ ] In conversation with Ravel, certain options that should increase morale of characters actually makes them panic
- [ ] Shadows that spawn in ravels maze can still attack you while you are watching the end cutscene
- [ ] Thokola near the mage in carceri/curst do not respond to his help action and attack the player
- [ ] Carceri Gate : the gate initiates dialogue repeatedly, even though it is meant to be a one off
- [ ] Should cutscene mode disable fog? When Morte is kidnapped, some of the cutscene is not visible
- [ ] Is Mantuok supposed to block your passage back to Lothar until you have what he wants?
- [ ] Alleyway AR0405 : a0405fac.bam should freeze at the end of the cycle, right now it repeats 
- [ ] Annah initiates the dialog with the alley, so we get her portrait instead of TNO

_[these untracked issues I will research more into when I reach them in game]_

**Comment by lynxlynxlynx** [comment]
> In conversation with Ravel, certain options that should increase morale of characters actually makes them panic
I think this one was fixed already — with the proper pst morale implementation.

**Comment by chilvence** [comment]
I will re-test the ravel maze, I remember that fix going in, but this area must have slipped my mind at the time.

**Comment by lynxlynxlynx** [comment]
Worldmap travel does not use the right entry points <-- this one deserves its own report. I just got an idea, perhaps we can infer the exit/entrance from their names. Eg. the two in ar0500 are both in the format of fr0000 and to0000, matching.

**Comment by chilvence** [comment]
I had this one on the "research later" pile but it might be simpler than I though. All the areas that you can access via the worldmap have an entrance named 'frommap'

This adds up with the behaviour of the original game - when you start being able to worldmap travel, you appear in a roughly central place on the map.

**Comment by lynxlynxlynx** [comment]
Nice, that's it then. :)

**Comment by lynxlynxlynx** [comment]
Looking at the entrances, sadly none of the maps in my GOG install appear to have any named "frommap".

**Comment by MarcelHB** [comment]
My second full run of game in GemRB (except for being blocked #2318 that I may need to resolve manually meanwhile). The experience felt more polished than IWD2, but the main problems I currently consider:

* Things that may have their root cause in #1665: Sometimes when quest related things did not work out as expected (Death Nation, Forgery) I was paranoid about the variables and dialog trees. It probably deserves its own full re-check once this is considered solved.
* Pathfinding performance: Not sure if some performance regression in the meantime is to blame, or if the map design is contributing here, but this is currently bad to the extent of unplayability. Some Sigil maps virtually prevent the player from walking around due to going into 3 FPS for some time intermittently, but also the Curst Prison was a pain.
* _Path abandoned + close to the goal_ situations frequently drain the dynamic from every fight (and this game is 95% close combat) since everybody is just standing around until the PCs are being moved around actively. Since this affects both PCs and enemies, it's somewhat balanced. Still it's micro management to carefully watch who has engaged in fighting or if some healing has actually taken place.
