### ISSUE TITLE
 0.8.8 Release checklist

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#912]
Nothing to see yet, just creating to queue extraordinary docs updates.

### Release checklist

This is a general release preparation checklist to be used in the final stages of preparing
a new release.

Final development:
- [x] Fix or postpone issues in the [milestone](https://github.com/gemrb/gemrb/milestones)
- [x] Triage open pull requests
- [x] Check local stashes
- [x] No Coverity Scan issues

Beta testing:
- [x] Retest character generation of all games
- [x] Playthrough: Chateau Irenicus to Waukeen's promenade
- [x] Playthrough: TOB up to Saradush
- [x] Playthrough: iwd1 intro cutscenes
- [x] Playthrough: iwd2 intro cutscenes
- [x] Playthrough: pst intro cutscene

Release:
- [x] Finalise choice of version number, eg. v1.2.3
- [x] Update version number in `gemrb/includes/globals.h`
- [x] Final `NEWS` update
- [x] Create the source tarball with `make dist`
  - [x] Add any missing files to the cmake install targets and recreate the tarball
  - [x] Add any new extraneous files to `.gitattributes` and recreate
  - [x] Build it and run the minimal test or more: `gemrb/gemrb -c ../gemrb/GemRB.cfg.noinstall.sample`
- [x] Add a git tag and push it
    ```
        ver=0.8.8
        git tag -a -m "GemRB $ver" v$ver
        git push origin v$ver
    ```

Deployment:
- [x] Promote the new tag to a release on GitHub
- [x] Write docs:
  - [x] Forum announcements
  - [x] Release notes if needed (configuration changes: -q + paths + Logging + GamepadPointerSpeed + VitaKeepAspectRatio, notes for packagers: config + maybe wait)
  - [x] fix docs on running with the new simplifications
- [x] SourceForge
  - [x] Upload source package to SourceForge, maintaining the naming format under Releases
    - [x] Upload any release notes alongside
  - [x] Mark release builds as OS defaults on SourceForge as appropriate; mark the source for everyone else
  - [x] Test downloads
- [x] Runtime tests of release packages
- [x] Announce on
  - [x] homepage: _config (bump version), index, news, potentially features/status, install (recheck the new links)
  - [x] Gibberlings3 forums
    - [x] GemRB forum
    - [x] modding news (a template is available in `admin/announcement.template`)
  - [x] SourceForge project page news section
  - [x] #GemRB in channel and title; Discord channel only if it doesn't propagate there automatically
  - [x] send to gemrb-release@lists.sourceforge.net, contact@gaminonlinux.com
  - [x] reddit, https://www.reddit.com/r/baldursgate/submit , Share->Crosspost to r/opensourcegames 
  - [x] bump version on wikidata

Post-release:
- [x] Run `admin/guidoc_wikifier.sh` (no params needed) and upload the new docs
- [x] Update versions back to the `-git` suffix
- [x] Run `admin/restart_news.sh` to restart the NEWS cycle
- [x] If the manpage changed (`git log v0.8.7.. gemrb.6.in`), adapt the web copy (pandoc can convert it to markdown)

2play, Alan1616, Alan1616, Balrog994, Bernd Schmidt, Brad Allred, Bubb13, Cowcat5150, Cristi Mitrana, Destroyer5150, FrElvire, Jaka Kranjc, Jan Petykiewicz, Kevin Michael Frick, Khaled Hosny, Laurie Chilvers, MarcelHB, Mariusz Obajtek, Northfear, Poligraf, Rodrigo Santellan, Ryein Goddard, SharkyRawr, Toulonnais72, afxgroup, bittin, burner1024, emorrp1, escalade, fenuks, fizzet, luke243, m7600, nerd-rage, neula, psilyntdev, rfht, samo79, tonyRecordOn
